SET(nstlroot_MAJOR_VERSION 0)
SET(nstlroot_MINOR_VERSION 5)
SET(nstlroot_BUILD_VERSION 0)

FIND_PACKAGE(Git)
IF(GIT_FOUND)
  EXECUTE_PROCESS(
    COMMAND ${GIT_EXECUTABLE} rev-parse --short HEAD
    WORKING_DIRECTORY "${CMAKE_CURRENT_LIST_DIR}"
    OUTPUT_VARIABLE "nstlroot_BUILD_VERSION"
    ERROR_QUIET
    OUTPUT_STRIP_TRAILING_WHITESPACE
  )
  MESSAGE(STATUS "NSTL version: ${nstlroot_BUILD_VERSION}")
ENDIF(GIT_FOUND)
SET(nstlroot_VERSION "${nstlroot_MAJOR_VERSION}.${nstlroot_MINOR_VERSION}.${nstlroot_BUILD_VERSION}")

if (WIN32)
  set(NSTL_USING_OPENSSL OFF CACHE BOOL "NSTL using OpenSSL")
else()
  set(NSTL_USING_OPENSSL ON CACHE BOOL "NSTL using OpenSSL")
endif()

try_compile(NSTL_USING_STD_CHRONO_IMPL
  ${CMAKE_CURRENT_BINARY_DIR}/temp
  ${CMAKE_CURRENT_LIST_DIR}/chrono_has_tzone.cpp
  OUTPUT_VARIABLE NSTL_USING_STD_CHRONO_OUT)

set(NSTL_USING_STD_CHRONO ${NSTL_USING_STD_CHRONO_IMPL} CACHE BOOL "")
MESSAGE(STATUS "Using C++20 std::chrono: ${NSTL_USING_STD_CHRONO}")

if(LINUX)
  try_compile(NSTL_HAVE_BACKTRACE ${CMAKE_CURRENT_BINARY_DIR}/temp ${CMAKE_CURRENT_LIST_DIR}/backtrace_is_around.cpp LINK_LIBRARIES backtrace OUTPUT_VARIABLE HAVE_BACKTRACE_OUT)
else(LINUX)
  set(NSTL_HAVE_BACKTRACE OFF)
  set(NSTL_HAVE_BACKTRACE_OUT "Feature is Linux only")
endif(LINUX)
if (NSTL_HAVE_BACKTRACE)
  message(STATUS "NSTL_HAVE_BACKTRACE: ${NSTL_HAVE_BACKTRACE}")
else(NSTL_HAVE_BACKTRACE)
  message(STATUS "NSTL_HAVE_BACKTRACE: ${NSTL_HAVE_BACKTRACE} - ${NSTL_HAVE_BACKTRACE_OUT}")
endif(NSTL_HAVE_BACKTRACE)
